# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: A
    jobs:
      - job:
        container: mcr.microsoft.com/dotnet/core/sdk:3.0
        steps:
          - task: DotNetCoreCLI@2
            inputs: 
              command: build
        
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '**/*Tests*.csproj'

  - stage: B
    jobs:
    - job:
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            echo 'Hello world'